/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class controllers_GetFiles */

#ifndef _Included_controllers_GetFiles
#define _Included_controllers_GetFiles
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     controllers_GetFiles
 * Method:    getFiles
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_controllers_GetFiles_getFiles
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
